workflows:
  ios-build:
    name: iOS Test Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "your-email@example.com"
